# Production Environment Configuration
api:
  base_url: "https://api.production.com"
  version: "v4"
  endpoints:
    auth_login: "/auth/login"
    auth_apple_login: "/auth/apple-login"
    hotels: "/hotels"

app:
  name: "SwiftUIPlayground"
  debug_mode: false
  timeout_interval: 60.0

features:
  logging: false
  analytics: true
  crash_reporting: true 